### ISSUE TITLE
TypeScript error due to missing typings for 'ws' dependency

### ISSUE THREAD

**Issue by richeterre** [infinitered/reactotron#1066]
I installed version `3.5.2` in my React Native project that uses TypeScript. Now when I run the TS compiler, I get the following error:

```
> tsc

node_modules/reactotron-core-client/dist/types/reactotron-core-client.d.ts:1:28 - error TS7016: Could not find a declaration file for module 'ws'. '/Users/Martin/Code/Donut/app/node_modules/ws/index.js' implicitly has an 'any' type.
  Try `npm install @types/ws` if it exists or add a new declaration (.d.ts) file containing `declare module 'ws';`

1 import * as WebSocket from "ws";
```

It seems that [`@types/ws`](https://www.npmjs.com/package/@types/ws)  is listed under `devDependencies` in this package. Should it be moved to `dependencies` instead?

**Comment by rmevans9** [comment]
Yes, most/all the types should likely be moved to dependencies. I will work on this.

**Comment by rmevans9** [comment]
`reactotron-react-native` 3.5.3 should resolve this issue!

**Comment by richeterre** [comment]
Hi @rmevans9, I'm seeing this issue again with `reactotron-react-native` version `3.6.4` after upgrading from `3.6.2`. Would you consider reopening?

**Comment by mrbrentkelly** [comment]
Seeing this in `reactotron-react-native` `3.6.5`

**Comment by richeterre** [comment]
@rmevans9 This is still happening in `reactotron-react-native` `4.0.0` unfortunately!

**Comment by rmevans9** [comment]
Hey @richeterre! Yeah, we ended up having to move them back to devDependencies because adding them to dependencies actually caused conflicting typings for some projects. I am actively looking for a better way around this issue but without forcing these typings into every project possibly causing conflicts I haven't found a good path forward.

**Comment by leotm** [comment]
Same here for `reactotron-react-native` `5.0.0`, so sticking to `yarn add -D @types/ws` for time being with commit msg pointing here (;
